### ISSUE TITLE
How does this experiment fit into OpenFaas

### ISSUE THREAD

**Issue by GitHubDiom** [Be-FaaS/BeFaaS-framework#5]
Hi there,

I have deployed openFaaS platform in minikube.

The [documentation](https://github.com/Be-FaaS/BeFaaS-framework/blob/master/doc/experiments.md) says that some configuration changes need to be made in the `experiment.json` file.

Could you please give more details about how to make such configuration changes?

Following are some errors occurs: (I did not change the configuration(`experiment.json`))
```shell
/experiments# npm run deploy webservice

> experiments@1.0.0 deploy /experiments
> ./scripts/deploy.sh "webservice"

Environment variable AWS_REGION should be set

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! experiments@1.0.0 deploy: `./scripts/deploy.sh "webservice"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the experiments@1.0.0 deploy script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-05-12T06_36_15_353Z-debug.log
```
```shell
/experiments# cat /root/.npm/_logs/2021-05-12T06_36_15_353Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'deploy',
1 verbose cli   'webservice'
1 verbose cli ]
2 info using npm@6.14.5
3 info using node@v12.18.2
4 verbose run-script [ 'predeploy', 'deploy', 'postdeploy' ]
5 info lifecycle experiments@1.0.0~predeploy: experiments@1.0.0
6 info lifecycle experiments@1.0.0~deploy: experiments@1.0.0
7 verbose lifecycle experiments@1.0.0~deploy: unsafe-perm in lifecycle true
8 verbose lifecycle experiments@1.0.0~deploy: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/experiments/node_modules/.bin:/usr/local/go/bin:/google-cloud-sdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle experiments@1.0.0~deploy: CWD: /experiments
10 silly lifecycle experiments@1.0.0~deploy: Args: [ '-c', './scripts/deploy.sh "webservice"' ]
11 silly lifecycle experiments@1.0.0~deploy: Returned: code: 1  signal: null
12 info lifecycle experiments@1.0.0~deploy: Failed to exec deploy script
13 verbose stack Error: experiments@1.0.0 deploy: `./scripts/deploy.sh "webservice"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid experiments@1.0.0
15 verbose cwd /experiments
16 verbose Linux 4.18.0-240.22.1.el8_3.x86_64
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "deploy" "webservice"
18 verbose node v12.18.2
19 verbose npm  v6.14.5
20 error code ELIFECYCLE
21 error errno 1
22 error experiments@1.0.0 deploy: `./scripts/deploy.sh "webservice"`
22 error Exit status 1
23 error Failed at the experiments@1.0.0 deploy script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```
Thankyou!

**Comment by a-azqueta** [comment]
Hi,

Any news about it? I'm trying to deploy it in OpenWhisk but I'm facing errors during the deploy process 

Thank you,

Ainhoa
